"""initial schema

Revision ID: 4ddf5e48d6aa
Revises: 
Create Date: 2026-03-21 20:11:25.487574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ddf5e48d6aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AppSettings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aiProvider', sa.String(), nullable=False),
    sa.Column('aiModel', sa.String(), nullable=True),
    sa.Column('mediumModel', sa.String(), nullable=True),
    sa.Column('lightModel', sa.String(), nullable=True),
    sa.Column('exploreModel', sa.String(), nullable=True),
    sa.Column('executeModel', sa.String(), nullable=True),
    sa.Column('titleModel', sa.String(), nullable=True),
    sa.Column('compactModel', sa.String(), nullable=True),
    sa.Column('llmProviderOverrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('useLightModel', sa.Boolean(), nullable=False),
    sa.Column('advancedModelConfig', sa.Boolean(), nullable=False),
    sa.Column('embeddingProvider', sa.String(), nullable=False),
    sa.Column('embeddingModel', sa.String(), nullable=True),
    sa.Column('openaiApiKey', sa.Text(), nullable=True),
    sa.Column('geminiApiKey', sa.Text(), nullable=True),
    sa.Column('anthropicApiKey', sa.Text(), nullable=True),
    sa.Column('localBaseUrl', sa.String(), nullable=True),
    sa.Column('onboardingComplete', sa.Boolean(), nullable=False),
    sa.Column('contextLimitTokens', sa.Integer(), nullable=False),
    sa.Column('browserGridUrl', sa.String(), nullable=True),
    sa.Column('browserGridApiKey', sa.Text(), nullable=True),
    sa.Column('browserGridBrowser', sa.String(), nullable=True),
    sa.Column('browserModel', sa.String(), nullable=True),
    sa.Column('maxAgentIterations', sa.Integer(), nullable=False),
    sa.Column('subAgentExploreMaxIterations', sa.Integer(), nullable=False),
    sa.Column('subAgentAnalyzeMaxIterations', sa.Integer(), nullable=False),
    sa.Column('subAgentExecuteMaxIterations', sa.Integer(), nullable=False),
    sa.Column('dismissedUpdateVersion', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('AppUpdateRun',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('currentVersion', sa.String(), nullable=True),
    sa.Column('targetVersion', sa.String(), nullable=False),
    sa.Column('targetReleaseName', sa.String(), nullable=True),
    sa.Column('targetReleaseUrl', sa.String(), nullable=True),
    sa.Column('targetPublishedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('targetReleaseNotes', sa.Text(), nullable=True),
    sa.Column('phaseMessage', sa.String(), nullable=True),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('AppUpdateRun_status_idx', 'AppUpdateRun', ['status'], unique=False)
    op.create_index('AppUpdateRun_targetVersion_idx', 'AppUpdateRun', ['targetVersion'], unique=False)
    op.create_table('Capability',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('toolDefinitions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('systemPrompt', sa.Text(), nullable=False),
    sa.Column('dockerImage', sa.String(), nullable=True),
    sa.Column('packages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('networkAccess', sa.Boolean(), nullable=False),
    sa.Column('configSchema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authType', sa.String(), nullable=True),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('globalConfig', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skillType', sa.String(), nullable=True),
    sa.Column('installationScript', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('skillFileKey', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('CronJob',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('handler', sa.String(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('workspaceId', sa.String(), nullable=True),
    sa.Column('sessionId', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('lastRunAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lastRunStatus', sa.String(), nullable=True),
    sa.Column('lastRunError', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GlobalSettings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('autoApproveRules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TokenUsage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('inputTokens', sa.Integer(), nullable=False),
    sa.Column('outputTokens', sa.Integer(), nullable=False),
    sa.Column('totalTokens', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('TokenUsage_date_idx', 'TokenUsage', ['date'], unique=False)
    op.create_index('TokenUsage_provider_idx', 'TokenUsage', ['provider'], unique=False)
    op.create_table('Workspace',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('autoExecute', sa.Boolean(), nullable=False),
    sa.Column('containerId', sa.String(), nullable=True),
    sa.Column('containerStatus', sa.String(), nullable=False),
    sa.Column('containerLastActivityAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Channel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspaceId', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspaceId', 'type', name='Channel_workspaceId_type_key')
    )
    op.create_index('Channel_workspaceId_idx', 'Channel', ['workspaceId'], unique=False)
    op.create_table('ChatSession',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspaceId', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('folderScope', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('agentState', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agentStateEncrypted', sa.Text(), nullable=True),
    sa.Column('agentStatus', sa.String(), nullable=False),
    sa.Column('lastReadAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contextSummary', sa.Text(), nullable=True),
    sa.Column('contextSummaryUpTo', sa.String(), nullable=True),
    sa.Column('lastInputTokens', sa.Integer(), nullable=True),
    sa.Column('linuxUser', sa.String(), nullable=True),
    sa.Column('sessionAllowRules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('externalChatId', sa.String(), nullable=True),
    sa.Column('lastMessageAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Folder',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('workspaceId', sa.String(), nullable=False),
    sa.Column('parentId', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parentId'], ['Folder.id'], ),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Folder_workspaceId_idx', 'Folder', ['workspaceId'], unique=False)
    op.create_table('WorkspaceCapability',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspaceId', sa.String(), nullable=False),
    sa.Column('capabilityId', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capabilityId'], ['Capability.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspaceId', 'capabilityId', name='WorkspaceCapability_workspaceId_capabilityId_key')
    )
    op.create_table('ChatMessage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sessionId', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('toolCalls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contentBlocks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sessionId'], ['ChatSession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ChatMessage_sessionId_idx', 'ChatMessage', ['sessionId'], unique=False)
    op.create_table('Document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('workspaceId', sa.String(), nullable=False),
    sa.Column('folderId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('fileUrl', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chunkCount', sa.Integer(), nullable=False),
    sa.Column('processingStep', sa.String(), nullable=True),
    sa.Column('processingPct', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folderId'], ['Folder.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('Document_workspaceId_idx', 'Document', ['workspaceId'], unique=False)
    op.create_table('SandboxSession',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspaceId', sa.String(), nullable=True),
    sa.Column('chatSessionId', sa.String(), nullable=False),
    sa.Column('containerId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('startedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stoppedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatSessionId'], ['ChatSession.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspaceId'], ['Workspace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('SandboxSession_chatSessionId_idx', 'SandboxSession', ['chatSessionId'], unique=False)
    op.create_table('ToolApproval',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chatSessionId', sa.String(), nullable=False),
    sa.Column('toolName', sa.String(), nullable=False),
    sa.Column('capabilitySlug', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('toolCallId', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decidedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatSessionId'], ['ChatSession.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ToolApproval_chatSessionId_idx', 'ToolApproval', ['chatSessionId'], unique=False)
    op.create_table('DocumentChunk',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('documentId', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('qdrantId', sa.String(), nullable=False),
    sa.Column('chunkIndex', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['documentId'], ['Document.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qdrantId')
    )
    op.create_index('DocumentChunk_documentId_idx', 'DocumentChunk', ['documentId'], unique=False)
    op.create_table('ToolExecution',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sandboxSessionId', sa.String(), nullable=True),
    sa.Column('chatMessageId', sa.String(), nullable=True),
    sa.Column('capabilitySlug', sa.String(), nullable=False),
    sa.Column('toolName', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('screenshot', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('exitCode', sa.Integer(), nullable=True),
    sa.Column('durationMs', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chatMessageId'], ['ChatMessage.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sandboxSessionId'], ['SandboxSession.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ToolExecution_chatMessageId_idx', 'ToolExecution', ['chatMessageId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ToolExecution_chatMessageId_idx', table_name='ToolExecution')
    op.drop_table('ToolExecution')
    op.drop_index('DocumentChunk_documentId_idx', table_name='DocumentChunk')
    op.drop_table('DocumentChunk')
    op.drop_index('ToolApproval_chatSessionId_idx', table_name='ToolApproval')
    op.drop_table('ToolApproval')
    op.drop_index('SandboxSession_chatSessionId_idx', table_name='SandboxSession')
    op.drop_table('SandboxSession')
    op.drop_index('Document_workspaceId_idx', table_name='Document')
    op.drop_table('Document')
    op.drop_index('ChatMessage_sessionId_idx', table_name='ChatMessage')
    op.drop_table('ChatMessage')
    op.drop_table('WorkspaceCapability')
    op.drop_index('Folder_workspaceId_idx', table_name='Folder')
    op.drop_table('Folder')
    op.drop_table('ChatSession')
    op.drop_index('Channel_workspaceId_idx', table_name='Channel')
    op.drop_table('Channel')
    op.drop_table('Workspace')
    op.drop_index('TokenUsage_provider_idx', table_name='TokenUsage')
    op.drop_index('TokenUsage_date_idx', table_name='TokenUsage')
    op.drop_table('TokenUsage')
    op.drop_table('GlobalSettings')
    op.drop_table('CronJob')
    op.drop_table('Capability')
    op.drop_index('AppUpdateRun_targetVersion_idx', table_name='AppUpdateRun')
    op.drop_index('AppUpdateRun_status_idx', table_name='AppUpdateRun')
    op.drop_table('AppUpdateRun')
    op.drop_table('AppSettings')
    # ### end Alembic commands ###
